fix: modified migration sql (#34)
* fix: modified migration sql
- Removed commands that had already been applied before (the changes were not tracked)
- see commit 60ff5a224b857c34fb20e2735347928af98d29d8

* fix: bug in edit profile
- initially editing a profile resulted in the wrong profile being edited
- also added confirmation modals for better UI/UX.
- This included the change for PR #32

* fix: live compilation error
- Fixed error: Optional fields were not processed properly for the live rendering
- Slight increase in debounce interval for UX
- Minor change to button arrangements in confirmation modal